//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamrahanSystem.Presntation.Resources {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceCustomLensIndexes {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCustomLensIndexes() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HamrahanSystem.Presntation.Resources.ResourceCustomLensIndexes", typeof(ResourceCustomLensIndexes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Column_Brand {
            get {
                return ResourceManager.GetString("Column_Brand", resourceCulture);
            }
        }

        public static string Column_Id {
            get {
                return ResourceManager.GetString("Column_Id", resourceCulture);
            }
        }

        public static string Column_LensType {
            get {
                return ResourceManager.GetString("Column_LensType", resourceCulture);
            }
        }

        public static string Column_DesignType {
            get {
                return ResourceManager.GetString("Column_DesignType", resourceCulture);
            }
        }

        public static string Column_LensIndex {
            get {
                return ResourceManager.GetString("Column_LensIndex", resourceCulture);
            }
        }

        public static string Column_ColoringType {
            get {
                return ResourceManager.GetString("Column_ColoringType", resourceCulture);
            }
        }

        public static string Column_OrderId {
            get {
                return ResourceManager.GetString("Column_OrderId", resourceCulture);
            }
        }

        public static string Column_IsActive {
            get {
                return ResourceManager.GetString("Column_IsActive", resourceCulture);
            }
        }

        public static string Column_EditDelete {
            get {
                return ResourceManager.GetString("Column_EditDelete", resourceCulture);
            }
        }
    }
}
