//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamrahanSystem.Presntation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcePages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcePages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HamrahanSystem.Presntation.Resources.ResourcePages", typeof(ResourcePages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت و ارسال.
        /// </summary>
        public static string AddSend {
            get {
                return ResourceManager.GetString("AddSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis.
        /// </summary>
        public static string Base_Axis {
            get {
                return ResourceManager.GetString("Base_Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بار کد کالا.
        /// </summary>
        public static string Base_BarCode {
            get {
                return ResourceManager.GetString("Base_BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Base_Brand {
            get {
                return ResourceManager.GetString("Base_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string Base_Code {
            get {
                return ResourceManager.GetString("Base_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصرف کننده.
        /// </summary>
        public static string Base_Consumer {
            get {
                return ResourceManager.GetString("Base_Consumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CYL.
        /// </summary>
        public static string Base_Cyl {
            get {
                return ResourceManager.GetString("Base_Cyl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری.
        /// </summary>
        public static string Base_DefineCustomer {
            get {
                return ResourceManager.GetString("Base_DefineCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا انبار.
        /// </summary>
        public static string Base_DefineObject {
            get {
                return ResourceManager.GetString("Base_DefineObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Base_Description {
            get {
                return ResourceManager.GetString("Base_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Type.
        /// </summary>
        public static string Base_DesignType {
            get {
                return ResourceManager.GetString("Base_DesignType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چشم.
        /// </summary>
        public static string Base_EyeSide {
            get {
                return ResourceManager.GetString("Base_EyeSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره فاکتور.
        /// </summary>
        public static string Base_Factore {
            get {
                return ResourceManager.GetString("Base_Factore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره.
        /// </summary>
        public static string Base_Id {
            get {
                return ResourceManager.GetString("Base_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت(فعال/غیرفعال).
        /// </summary>
        public static string Base_IsActive {
            get {
                return ResourceManager.GetString("Base_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیر سیستم.
        /// </summary>
        public static string Base_IsAdmin {
            get {
                return ResourceManager.GetString("Base_IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش تعداد با بارکد خوان.
        /// </summary>
        public static string Base_IsBarcode {
            get {
                return ResourceManager.GetString("Base_IsBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چاپ  خودکار.
        /// </summary>
        public static string Base_IsPrint {
            get {
                return ResourceManager.GetString("Base_IsPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش در عدسی سفارشی ؟.
        /// </summary>
        public static string Base_IsSpecial {
            get {
                return ResourceManager.GetString("Base_IsSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش در عدسی آماده؟.
        /// </summary>
        public static string Base_IsStock {
            get {
                return ResourceManager.GetString("Base_IsStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش در عدسی آماده  گارانتی؟.
        /// </summary>
        public static string Base_IsStockGranty {
            get {
                return ResourceManager.GetString("Base_IsStockGranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lens Index.
        /// </summary>
        public static string Base_LensIndex {
            get {
                return ResourceManager.GetString("Base_LensIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lens Type.
        /// </summary>
        public static string Base_LensType {
            get {
                return ResourceManager.GetString("Base_LensType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Type.
        /// </summary>
        public static string Base_MaterialType {
            get {
                return ResourceManager.GetString("Base_MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Base_Name {
            get {
                return ResourceManager.GetString("Base_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوازم.
        /// </summary>
        public static string Base_NeedTools {
            get {
                return ResourceManager.GetString("Base_NeedTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتیب نمایش.
        /// </summary>
        public static string Base_OrderId {
            get {
                return ResourceManager.GetString("Base_OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعالیت درخواستی .
        /// </summary>
        public static string Base_ProcedureId {
            get {
                return ResourceManager.GetString("Base_ProcedureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان فرآیند.
        /// </summary>
        public static string Base_Process {
            get {
                return ResourceManager.GetString("Base_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تایید شده انبار.
        /// </summary>
        public static string Base_ProvidedQuantity {
            get {
                return ResourceManager.GetString("Base_ProvidedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string Base_Quantity {
            get {
                return ResourceManager.GetString("Base_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPH.
        /// </summary>
        public static string Base_Sph {
            get {
                return ResourceManager.GetString("Base_Sph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشگاه.
        /// </summary>
        public static string Base_StoreName {
            get {
                return ResourceManager.GetString("Base_StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LensType مرتبط.
        /// </summary>
        public static string BrandLensType {
            get {
                return ResourceManager.GetString("BrandLensType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LensType مرتبط.
        /// </summary>
        public static string BrandLensTypeR {
            get {
                return ResourceManager.GetString("BrandLensTypeR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brands {
            get {
                return ResourceManager.GetString("Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coating.
        /// </summary>
        public static string Coatings {
            get {
                return ResourceManager.GetString("Coatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coloring.
        /// </summary>
        public static string ColoringTypes {
            get {
                return ResourceManager.GetString("ColoringTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ و زمان ایجاد.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری.
        /// </summary>
        public static string CustomerId {
            get {
                return ResourceManager.GetString("CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyl.
        /// </summary>
        public static string Cyles {
            get {
                return ResourceManager.GetString("Cyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lens index مرتبط.
        /// </summary>
        public static string DesignTypeLensIndexs {
            get {
                return ResourceManager.GetString("DesignTypeLensIndexs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string DesignTypes {
            get {
                return ResourceManager.GetString("DesignTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره فاکتور.
        /// </summary>
        public static string FactorNo {
            get {
                return ResourceManager.GetString("FactorNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame.
        /// </summary>
        public static string FrameTypes {
            get {
                return ResourceManager.GetString("FrameTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  فرآیند عدسی .
        /// </summary>
        public static string IndexDocument {
            get {
                return ResourceManager.GetString("IndexDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sph مرتبط.
        /// </summary>
        public static string LenIndexRSph {
            get {
                return ResourceManager.GetString("LenIndexRSph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Types مرتبط.
        /// </summary>
        public static string LensIndexMaterialTypes {
            get {
                return ResourceManager.GetString("LensIndexMaterialTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lens Index.
        /// </summary>
        public static string LensIndexRs {
            get {
                return ResourceManager.GetString("LensIndexRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lens Index.
        /// </summary>
        public static string LensIndexs {
            get {
                return ResourceManager.GetString("LensIndexs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to design type مرتبط.
        /// </summary>
        public static string LensTypeDesignTypes {
            get {
                return ResourceManager.GetString("LensTypeDesignTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lens Index مرتبط.
        /// </summary>
        public static string LensTypeRLenIndexR {
            get {
                return ResourceManager.GetString("LensTypeRLenIndexR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lens Type.
        /// </summary>
        public static string LensTypeRs {
            get {
                return ResourceManager.GetString("LensTypeRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lens Type.
        /// </summary>
        public static string LensTypes {
            get {
                return ResourceManager.GetString("LensTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارشها.
        /// </summary>
        public static string ListOrder {
            get {
                return ResourceManager.GetString("ListOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بررسی سفارشها.
        /// </summary>
        public static string ListReqOrder {
            get {
                return ResourceManager.GetString("ListReqOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string MaterialTypes {
            get {
                return ResourceManager.GetString("MaterialTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن همراه.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت درخواست.
        /// </summary>
        public static string OrderRequest {
            get {
                return ResourceManager.GetString("OrderRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت سفارش.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحله سفارش.
        /// </summary>
        public static string OrderStep {
            get {
                return ResourceManager.GetString("OrderStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدسی آماده (عمده).
        /// </summary>
        public static string OrderStock {
            get {
                return ResourceManager.GetString("OrderStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدسی آماده با کارت گارانتی.
        /// </summary>
        public static string OrderStockGranty {
            get {
                return ResourceManager.GetString("OrderStockGranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع سفارش.
        /// </summary>
        public static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرآیندها.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز عبور.
        /// </summary>
        public static string RePassword {
            get {
                return ResourceManager.GetString("RePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست .
        /// </summary>
        public static string Requestes {
            get {
                return ResourceManager.GetString("Requestes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مورد نیاز درخواست.
        /// </summary>
        public static string RequestFeildes {
            get {
                return ResourceManager.GetString("RequestFeildes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراحل بررسی درخواست.
        /// </summary>
        public static string RequestSteps {
            get {
                return ResourceManager.GetString("RequestSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه دسترسی.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزییات درخواست.
        /// </summary>
        public static string ShowReport {
            get {
                return ResourceManager.GetString("ShowReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cyl مرتبط.
        /// </summary>
        public static string SphCylR {
            get {
                return ResourceManager.GetString("SphCylR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cyl مرتبط.
        /// </summary>
        public static string SphCylRs {
            get {
                return ResourceManager.GetString("SphCylRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sph.
        /// </summary>
        public static string Sphs {
            get {
                return ResourceManager.GetString("Sphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گام های  فرآیند.
        /// </summary>
        public static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
