//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamrahanSystem.Presntation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceAlert {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceAlert() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HamrahanSystem.Presntation.Resources.ResourceAlert", typeof(ResourceAlert).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ثبت اطلاعات.
        /// </summary>
        public static string AddError {
            get {
                return ResourceManager.GetString("AddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت ثبت شد.
        /// </summary>
        public static string AddSucces {
            get {
                return ResourceManager.GetString("AddSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر وضعیت انجام شد .
        /// </summary>
        public static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مشتری را انتخاب نمایید.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در فراخوانی اطلاعات .
        /// </summary>
        public static string MessageErrorLoadJq {
            get {
                return ResourceManager.GetString("MessageErrorLoadJq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد عدسی بیشتر از تعداد درخواستها است .
        /// </summary>
        public static string OverFlowLens {
            get {
                return ResourceManager.GetString("OverFlowLens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده انتخابی با موفقیت حذف گردید.
        /// </summary>
        public static string RemoveSuccess {
            get {
                return ResourceManager.GetString("RemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت جهت بررسی ارسال شد.
        /// </summary>
        public static string SendSuccess {
            get {
                return ResourceManager.GetString("SendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کالا نمیتواند صفر باشد.
        /// </summary>
        public static string ZeroQuantity {
            get {
                return ResourceManager.GetString("ZeroQuantity", resourceCulture);
            }
        }
    }
}
