//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/29/2025 11:23:12 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace HamrahanSystem.Application.DTOs
{

    public partial class TblWfwOrderProcessDto
    {
        #region Constructors

        public TblWfwOrderProcessDto() {
        }

        public TblWfwOrderProcessDto(System.DateTime? dateComplete, System.DateTime dateCreate, long orderId, long orderProcessId, int processId, int statusId, TblWfwProcessDto tblWfwProcess, TblLnsOrderDto tblLnsOrder, List<TblWfwOrderProcessStepDto> tblWfwOrderProcessSteps) {

          this.DateComplete = dateComplete;
          this.DateCreate = dateCreate;
          this.OrderId = orderId;
          this.OrderProcessId = orderProcessId;
          this.ProcessId = processId;
          this.StatusId = statusId;
          this.TblWfwProcess = tblWfwProcess;
          this.TblLnsOrder = tblLnsOrder;
          this.TblWfwOrderProcessSteps = tblWfwOrderProcessSteps;
        }

        #endregion

        #region Properties

        public System.DateTime? DateComplete { get; set; }

        public System.DateTime DateCreate { get; set; }

        public long OrderId { get; set; }

        public long OrderProcessId { get; set; }

        public int ProcessId { get; set; }

        public int StatusId { get; set; }

        #endregion

        #region Navigation Properties

        public TblWfwProcessDto TblWfwProcess { get; set; }

        public TblLnsOrderDto TblLnsOrder { get; set; }

        public List<TblWfwOrderProcessStepDto> TblWfwOrderProcessSteps { get; set; }

        #endregion
    }

}
