//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 9/28/2025 11:25:51 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace HamrahanSystem.Domain.Entity
{
    public partial class TblMainDefineUser {

        public TblMainDefineUser()
        {
            this.IsDisableTriggers = false;
            OnCreated();
        }

        /// <summary>
        /// NoActive=0 , Active=1
        /// </summary>
        public bool? Active { get; set; }

        /// <summary>
        /// نام شخص
        /// </summary>
        public string CodePersona { get; set; }

        /// <summary>
        /// کد شرکت
        /// </summary>
        public byte Company { get; set; }

        public int Id { get; set; }

        public bool IsDisableTriggers { get; set; }

        /// <summary>
        /// کلمه عبور
        /// </summary>
        public string PassWord { get; set; }

        public long? PassWordCheck { get; set; }

        public string PictureNo { get; set; }

        public int? RNPersona { get; set; }

        public string SQLPassword { get; set; }

        public string SQLUserName { get; set; }

        /// <summary>
        /// کد کاربر
        /// </summary>
        public int UserID { get; set; }

        /// <summary>
        /// نام کاربر
        /// </summary>
        public string UserName { get; set; }

        public string WebPassword { get; set; }

        public string WebServer { get; set; }

        public string WebUserName { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          TblMainDefineUser toCompare = obj as TblMainDefineUser;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Company, toCompare.Company))
            return false;
          if (!Object.Equals(this.UserID, toCompare.UserID))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Company.GetHashCode();
          hashCode = (hashCode * 7) + UserID.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
